runtime: python27
api_version: 1
threadsafe: true
version: 16
application: ms-image-analysis

handlers:
- url: /.*
  script: app.app
  
libraries:
- name: pycrypto
  version: "latest"   
- name: jinja2
  version: "latest"  